require("core.plugin_config.nvim-tree")
require("core.plugin_config.markdown-preview")
require("core.plugin_config.lsp")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.autoclose")
require("core.plugin_config.onedark")
