require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.onedark")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.autoclose")
