require("core.plugin_config.nvim-tree")
require("core.plugin_config.vimtex")
require("core.plugin_config.markdown-preview")
require("core.plugin_config.lsp")
require("core.plugin_config.treesitter")
require("core.plugin_config.cmp")
require("core.plugin_config.telescope")
require("core.plugin_config.autoclose")
